import { existsSync, mkdirSync } from "node:fs";
import { expect, test as setup } from "@playwright/test";

import {
  ACCEPTANCE_PASSWORD,
  ROLES,
  type Role,
  storageStatePath,
} from "./support/roles";

/**
 * Log each role in once and cache its browser state.
 *
 * Re-logging in before every test costs minutes across a suite and makes
 * Keycloak the thing most likely to make it flake, for no coverage in return.
 * The login flow itself is exercised here, once, on every run.
 */

setup.beforeAll(() => {
  if (!ACCEPTANCE_PASSWORD) {
    throw new Error(
      "KEYCLOAK_E2E_USER_PASSWORD is not set, so no acceptance user can log " +
        "in. It is generated by ./scripts/bootstrap-local-env.sh and applied " +
        "by the keycloak-bootstrap job.",
    );
  }
  if (!existsSync("e2e/.auth")) {
    mkdirSync("e2e/.auth", { recursive: true });
  }
});

for (const role of ROLES) {
  setup(`authenticate as ${role}`, async ({ page }) => {
    await page.goto("/");

    // The app redirects to Keycloak when unauthenticated. Waiting for the
    // username field is both the wait and the assertion that it happened.
    const username = page.locator("#username");
    await expect(
      username,
      `expected a Keycloak login form for ${role}; the app may not be in keycloak auth mode`,
    ).toBeVisible();

    await username.fill(role);
    await page.locator("#password").fill(ACCEPTANCE_PASSWORD);
    await page.locator("#kc-login").click();

    // Landing back on the app, with the role's identity resolved, is what
    // proves the round trip worked.
    await expect(
      page.getByRole("navigation"),
      `${role} did not reach the application after login`,
    ).toBeVisible();

    await page.context().storageState({ path: storageStatePath(role as Role) });
  });
}
