-- NeuroX schema is owned by Alembic and SQLAlchemy metadata.
-- Apply with: cd services/api && alembic upgrade head
-- This file intentionally contains no second, drifting schema definition.
-- See services/api/alembic/versions/fa2f4a40b692_baseline.py.
